[package]
name = "rusty_64"
version = "0.1.0"
authors = ["max <none@none.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
num = "0.1.30"
enum_primitive = "0.1.0"
